consumer:
  max_retry_count: 3
  prefetch: 1
  delay_time: 1 # 1 min
  waitForPendingMessages: true #For Graceful Shutdown
connection:
  port: 3000
  rabbitMQ: amqp://user:password@localhost:5672
  # mongoDB: mongodb://user:password@example_mongodb:27017/database?authSource=admin&retryWrites=true&w=majority
logger:
  console:
    level: debug
  file:
    level: error
  silent: false
